name: QA Book Scraper Tests

on:
  push:
    branches: [none] # main
  pull_request:
    branches: [none] # main

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare folders
        run: |
          mkdir reports
          mkdir outputs

      - name: Run tests
        run: |
          pytest --html=reports/report.html --self-contained-html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/report.html

      - name: Upload Excel results
        uses: actions/upload-artifact@v4
        with:
          name: excel-test-results
          path: outputs/
